### PR TITLE
Fibonacci Series in Python

### PR DESCRIPTION
**Pull request by chiragjagad**
Fibonacci Series in Python

### CODE REVIEW

**Review by deutranium — COMMENTED** [review]
@chiragjagad This code has already been implemented. Check the repo or issue #14 for reference. If you think you can improvise, kindly edit the file already there.

Also, before contributing, kindly check if someone else has worked on/is working on the code you want to contribute, otherwise it is just a waste of effort

**Comment by chiragjagad** [comment]
> @chiragjagad This code has already been implemented. Check the repo or issue #14 for reference. If you think you can improvise, kindly edit the file already there.
> 
> Also, before contributing, kindly check if someone else has worked on/is working on the code you want to contribute, otherwise it is just a waste of effort
> 
> If you can add something which is not there already, kindly do so or I'll have to close this PR without merging.

So, should I implement it in Java or should I take something new? Please assign to me

**Comment by deutranium** [comment]
@chiragjagad sure. I've assigned JAVA to you. Please comment on the issue #14 after that I'll be able to add you as an assignee there.

**Comment by deutranium** [comment]
Closing this as the issue has been resolved in #14

**Pull request closed without merging**
