### PR TITLE
Create Lua sorting algorithms.

### PR DESCRIPTION
**Pull request by shawnjb**
This PR implements the code for sorting in Lua.

I have read the contributing guidelines in [CONTRIBUTING.md](https://github.com/deutranium/Algorithms/blob/master/CONTRIBUTING.md) and have ensured the following:

- [X] My code is placed in the required directory as outlined in [CONTRIBUTING.md](https://github.com/deutranium/Algorithms/blob/master/CONTRIBUTING.md)
- [X] My code file is named according to [CONTRIBUTING.md](https://github.com/deutranium/Algorithms/blob/master/CONTRIBUTING.md)
- [X] Variables, classes, functions etc. follow camel case as outlined in [CONTRIBUTING.md](https://github.com/deutranium/Algorithms/blob/master/CONTRIBUTING.md)
- [X] My code hasn't been implemented or claimed by someone else and I have checked the present [issues](https://github.com/deutranium/Algorithms/issues) and [PRs](https://github.com/deutranium/Algorithms/pulls) for the same
- [X] **My code is well commented**
- [X] I have **not** copied my code from anywhere

### CODE REVIEW

**Comment by shawnjb** [comment]
This is complete, and is ready for merging.

**Comment by codelixir** [comment]
Please remove .vscode/settings.json from your PR.
While you're at it, can you add .vscode to .gitignore as well? Thanks

**Comment by shawnjb** [comment]
Sure.

**Comment by codelixir** [comment]
Merged; sorry for the delay.
Thanks for contributing!

**Pull request merged**
